# Dockerfile based on the latest centos 7 image - non privilage user image
FROM centos:latest
MAINTAINER vlvanchin@gmail.com

RUN useradd -ms /bin/bash user

CMD "echo" "This is a custom container message for students"

USER user

