version: "3"
services:
  web:
    # the image to be used
    image: friendlyhello:latest
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.1"
          memory: '50M'
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:
