server:
  port: 0
  
spring:
  ldap:
    embedded:
      ldif: resources:test-server.ldif
      port: 389
      validation:
        enabled: false
      base-dn: dc=springframework, dc=com
      credential:
        username: uid=admin
        password: secret