-
  name: Deploy a mysql DB
  hosts: db_server
  roles:
    - python
    - mysql_db


-
  name: Deploy a Web Server
  hosts: web_server
  roles:
    - python
    - flask_web

-
  name: Monitor Web Application for 6 Minutes
  hosts: web_server
  command: /opt/monitor_webapp.py
  # this play will run for 6 Minutes
  async: 360
  # this play will poll the hosts for every 30 seconds
  # putting a value 0 instead of 30 would lead to 'fire and forget' method
  poll: 30
  # the play response or result can be stored into a variable
  register: webapp_result

-
  name: Monitory DB application for 6 Minutes
  hosts: db_server
  command: /opt/monitor_db.py
  async: 360
  poll: 30
  register: database_result
