-
  name: Test Connectivity
  hosts: web_server
  vars:
    # this lookup plugin reads the csvfile type and looks for web_server
    ansible_ssh_pass: "{{ lookup('csvfile', 'web_server file=credentials.csv delimiter=,') }}"
  tasks:
  - name: Ping target host
    ping:
      data: "Test"
